export const USERS_GET_REQUESTED = 'USERS::GET_REQUESTED';
export const USERS_GET_SUCCEEDED = 'USERS::GET_SUCCEEDED';
export const USERS_GET_FAILED = 'USERS::GET_FAILED';

export const USERS_ADD_REQUESTED = 'USERS::ADD_REQUESTED';
export const USERS_ADD_SUCCEEDED = 'USERS::ADD_SUCCEEDED';
export const USERS_ADD_FAILED = 'USERS::ADD_FAILED';

export const USERS_LOGIN_REQUESTED = 'USERS::LOGIN_REQUESTED';
export const USERS_LOGIN_SUCCEEDED = 'USERS::LOGIN_SUCCEEDED';
export const USERS_LOGIN_FAILED = 'USERS::LOGIN_FAILED';

export const USERS_LOGOUT_REQUESTED = 'USERS::LOGOUT_REQUESTED';
export const USERS_LOGOUT_SUCCEEDED = 'USERS::LOGOUT_SUCCEEDED';
export const USERS_LOGOUT_FAILED = 'USERS::LOGOUT_FAILED';