export const USERS_GET_REQUESTED = 'USERS::GET_REQUESTED';
export const USERS_GET_SUCCEEDED = 'USERS::GET_SUCCEEDED';
export const USERS_GET_FAILED = 'USERS::GET_FAILED';

export const USERS_ADD_REQUESTED = 'USERS::ADD_REQUESTED';
export const USERS_ADD_SUCCEEDED = 'USERS::ADD_SUCCEEDED';
export const USERS_ADD_FAILED = 'USERS::ADD_FAILED';